services:
  postgresql:
    container_name: ${CONTAINER_NAME}
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256" # Force l'authentification (connexion locale et distant)
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      # Volume persistant local a chaque developpeur
      - postgres_data:/var/lib/postgresql/data  
      # Definition des schemas
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
 postgres_data: